-- MySQL Script generated by MySQL Workbench
-- Wed May  3 18:34:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `new_schema1` ;
USE `new_schema1` ;

-- -----------------------------------------------------
-- Table `new_schema1`.`agencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`agencias` (
  `numero_da_agencia` INT NOT NULL,
  `nome_gerente` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_da_agencia`),
  UNIQUE INDEX `numero_da_agencia_UNIQUE` (`numero_da_agencia` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`contas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`contas` (
  `numero_da_conta` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `saldo` FLOAT NULL DEFAULT 0,
  `agencias_numero_da_agencia` INT NOT NULL,
  PRIMARY KEY (`numero_da_conta`, `agencias_numero_da_agencia`),
  UNIQUE INDEX `numero_da_conta_UNIQUE` (`numero_da_conta` ASC) VISIBLE,
  INDEX `fk_contas_agencias1_idx` (`agencias_numero_da_agencia` ASC) VISIBLE,
  CONSTRAINT `fk_contas_agencias1`
    FOREIGN KEY (`agencias_numero_da_agencia`)
    REFERENCES `new_schema1`.`agencias` (`numero_da_agencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `new_schema1`.`transferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `new_schema1`.`transferencias` (
  `numero_da_transferencia` INT NOT NULL,
  `valor` FLOAT NULL DEFAULT 0,
  `contas_numero_da_conta` INT NOT NULL,
  `conta_destino` INT NOT NULL,
  `horario_tranferencia` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`numero_da_transferencia`, `contas_numero_da_conta`),
  UNIQUE INDEX `numero_do_extrato_UNIQUE` (`numero_da_transferencia` ASC) VISIBLE,
  INDEX `fk_transferencia_contas_idx` (`contas_numero_da_conta` ASC) VISIBLE,
  CONSTRAINT `fk_transferencia_contas`
    FOREIGN KEY (`contas_numero_da_conta`)
    REFERENCES `new_schema1`.`contas` (`numero_da_conta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'user1';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
